services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-search-backend
    ports:
      - "8001:8000"
    restart: unless-stopped
    volumes:
      - ./documents:/app/documents  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simple-search-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped